### ISSUE TITLE
Socket returns unknown error.

### ISSUE THREAD

**Issue by Jason57Fr** [fxcm/RestAPI#100]
Hello,

I am not able to use the python library. I got the following error message .

|INFO|2020-12-12 13:48:43,459|Connecting FXCM Server
|DEBUG|2020-12-12 13:48:43,460|Access token: 29e1f5b9f314ae12c7611b43e617c44d043c63ad.
|DEBUG|2020-12-12 13:48:43,542|Starting new HTTPS connection (1): api-demo.fxcm.com:443
|DEBUG|2020-12-12 13:48:44,198|https://api-demo.fxcm.com:443 "GET /socket.io/?access_token=29e1f5b9f314ae12c7611b43e617c44d043c63ad&agent=pythonquants&wait_for_connection=False&transport=polling&EIO=4&t=1607777323.460929 HTTP/1.1" 200 None
|ERROR|2020-12-12 13:48:44,200|Socket returns unknown error.

Here the code i used : 

import fxcmpy 
import socketio
TOKEN = '29e1f5b9f314ae12c7611b43e617c44d043c63ad'
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo', log_file='log.txt')
print(con.get_instruments())

I reinstall fxcmpy , socketio. Revoke the token and create a new one. Try on a second computer, but still same issue. Please advise.

fxcmpy version 1.2.6
socketio 5.0.1

**Comment by Jason57Fr** [comment]
Ok downgrade socketio to 4.6.1 fixed the issue.

**Comment by juannieblas** [comment]
I have the same issue
```
import fxcmpy
import socketio
TOKEN = 'TOKEN'
print(fxcmpy.__version__)
print(socketio.__version__)
con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo', log_file='log.txt')
print(con.get_instruments())

```
output
```
1.2.6
4.6.1
Traceback (most recent call last):
  File ".\main.py", line 7, in <module>
    con = fxcmpy.fxcmpy(access_token=TOKEN, log_level='debug', server='demo', log_file='log.txt')
  File "C:\Users\juanp\AppData\Local\Programs\Python\Python38\lib\site-packages\fxcmpy\fxcmpy.py", line 218, in __init__
    raise ServerError('Can not connect to FXCM Server.')
fxcmpy.fxcmpy.ServerError: Can not connect to FXCM Server.
```

**Comment by lspinheiro** [comment]
I have the same issue, but only when trying to connect from Linux environments (WSL and Docker), from Windows it works fine.

**Comment by Rajib-Kumar-Dey-Arch-PMP** [comment]
installing socketio version 4.6.1 worked for me in windows. Thanks who discovered it.

**Comment by trueToastedCode** [comment]
> Ok downgrade socketio to 4.6.1 fixed the issue.

Thank you so much... this works!

**Comment by YourGranny17** [comment]
how do you downgrade to socket 4.6.1 ?

**Comment by FXCMAPI** [comment]
(base) H:\>pip install python-socketio==4.6.1

**Comment by qianhuansky** [comment]
I am using windows 10

Successfully installed python-engineio-3.14.2 python-socketio-4.6.1

I still have the problem. 

|ERROR|2021-08-23 14:08:43,695|Socket returns unknown error.
---------------------------------------------------------------------------
ServerError                               Traceback (most recent call last)
<ipython-input-27-f09b47fa6648> in <module>
----> 1 api=fxcmpy.fxcmpy(access_token='d4ff3a7f9835aa0d36a9d922e08c378aea19194a', log_level='error')

~\anaconda3\lib\site-packages\fxcmpy\fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
--> 218             raise ServerError('Can not connect to FXCM Server.')
    219 
    220         self.__collect_account_ids__()

ServerError: Can not connect to FXCM Server.

**Comment by FXCMAPI** [comment]
Hi,

Are you able to try with:
python-socketio==4.4
python-engineio==3.9
websocket-client==1.1.0
And uninstalling socketio-client in case that you have it.

**Comment by qianhuansky** [comment]
I have tried. 


then I follow the steps mention in 1.6 in https://fxcmpy.tpq.io/00_quick_start.html#Disclaimer,
in jupyter notebook, then get:


---------------------------------------------------------------------------
ServerError                               Traceback (most recent call last)
<ipython-input-12-4a882c604ac7> in <module>
----> 1 con = fxcmpy.fxcmpy(access_token='b16420435c51dbfb6e95baf858bd17a190aac20c', log_level='error', server='demo', log_file='log.txt')


~\anaconda3\lib\site-packages\fxcmpy\fxcmpy.py in __init__(self, access_token, config_file, log_file, log_level, server, proxy_url, proxy_port, proxy_type)
    216             raise ServerError('Can not find FXCM Server.')
    217         elif self.connection_status == 'aborted':
--> 218             raise ServerError('Can not connect to FXCM Server.')
    219 
    220         self.__collect_account_ids__()


ServerError: Can not connect to FXCM Server.


Should I install something else?


| |
潜欢
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/23/2021 ***@***.***> wrote：

Hi,

Are you able to try with:
python-socketio==4.4
python-engineio==3.9
websocket-client==1.1.0
And uninstalling socketio-client in case that you have it.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FXCMAPI** [comment]
Hi,

Please try revoking a new access token from Trading Station.
Also maybe try to set server='demo2'

**Comment by qianhuansky** [comment]
Hi, 


I still can not connect to FXCM Server. 


| |
潜欢
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/23/2021 ***@***.***> wrote：

Hi,

Please try revoking a new access token from Trading Station.
Also maybe try to set server='demo2'

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FXCMAPI** [comment]
Hi,

Please share your demo token at api@fxcm.com

**Comment by qianhuansky** [comment]
f4788a1a423d3addd8be5d22b82a69c647570874
| |
潜欢
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/23/2021 ***@***.***> wrote：

Hi,

Please share your demo token at ***@***.***

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by perezjuang** [comment]
Today August 26 - 2022   is working with next version
    
    fxcmpy==1.3.3
    python-engineio==4.3.1
    python-socketio==5.0.4
    websocket-client==1.1.0
