### ISSUE TITLE
Where's the instrument_id?

### ISSUE THREAD

**Issue by dbvcode** [fxcm/RestAPI#111]
If I call `/trading/get_instruments` I do get a list of instruments like:
```
{ symbol: 'EUR/USD', visible: true, order: 100 },
{ symbol: 'USD/JPY', visible: true, order: 950 },
{ symbol: 'GBP/USD', visible: true, order: 250 },
{ symbol: 'USD/CHF', visible: true, order: 1250 },
{ symbol: 'EUR/CHF', visible: true, order: 1450 },
{ symbol: 'AUD/USD', visible: true, order: 1350 },
...
```
But there's no `id` for them? And what is `order` good for?

If I try to get _/candles/**instrument_id**/m5_  I need `instrument_id`.

Thanks for any help

**Comment by FXCMAPI** [comment]
Dear client

ID in order field

get_instruments has been executed: {'response': {'executed': True}, 'data': {'instrument': [{'symbol': 'EUR/USD', 'visible': True, 'order': 1}, {'symbol': 'USD/JPY', 'visible': False, 'order': 950}, {'symbol': 'GBP/USD', 'visible': True, 'order': 250}, {'symbol': 'USD/CHF', 'visible': True, 'order': 1250}, {'symbol': 'EUR/CHF', 'visible': True, 'order': 1450}, {'symbol': 'AUD/USD', 'visible': True, 'order': 1350}, {'symbol': 'USD/CAD', 'visible': True, 'order': 1750}, {'symbol': 'NZD/USD', 'visible': True, 'order': 1650}, {'symbol': 'EUR/GBP', 'visible': True, 'order': 1550}, {'symbol': 'EUR/JPY', 'visible': True, 'order': 850}, {'symbol': 'GBP/JPY', 'visible': True, 'order': 1050}, {'symbol': 'CHF/JPY', 'visible': True, 'order': 12}, {'symbol': 'GBP/CHF', 'visible': False, 'order': 13}, {'symbol': 'EUR/AUD', 'visible': True, 'order': 14}, {'symbol': 'EUR/CAD', 'visible': True, 'order': 15}, {'symbol': 'AUD/CAD', 'visible': True, 'order': 16}, {'symbol': 'AUD/JPY', 'visible': False, 'order': 1150}, {'symbol': 'CAD/JPY', 'visible': True, 'order': 18}, {'symbol': 'NZD/JPY', 'visible': True, 'order': 19}, {'symbol': 'GBP/CAD', 'visible': True, 'order': 20}, {'symbol': 'GBP/NZD', 'visible': True, 'order': 21}, {'symbol': 'GBP/AUD', 'visible': True, 'order': 1850}, {'symbol': 'AUD/NZD', 'visible': True, 'order': 28}, {'symbol': 'USD/SEK', 'visible': True, 'order': 30}, {'symbol': 'EUR/SEK', 'visible': True, 'order': 32}, {'symbol': 'EUR/NOK', 'visible': True, 'order': 36}, {'symbol': 'USD/NOK', 'visible': True, 'order': 37}, {'symbol': 'USD/MXN', 'visible': True, 'order': 38}, {'symbol': 'AUD/CHF', 'visible': True, 'order': 39}, {'symbol': 'EUR/NZD', 'visible': True, 'order': 40}, {'symbol': 'USD/ZAR', 'visible': True, 'order': 47}, {'symbol': 'USD/HKD', 'visible': False, 'order': 50}, {'symbol': 'ZAR/JPY', 'visible': True, 'order': 71}, {'symbol': 'USD/TRY', 'visible': True, 'order': 83}, {'symbol': 'EUR/TRY', 'visible': True, 'order': 87}, {'symbol': 'NZD/CHF', 'visible': True, 'order': 89}, {'symbol': 'CAD/CHF', 'visible': True, 'order': 90}, {'symbol': 'NZD/CAD', 'visible': True, 'order': 91}, {'symbol': 'TRY/JPY', 'visible': True, 'order': 98}, {'symbol': 'USD/CNH', 'visible': True, 'order': 799}, {'symbol': 'AUS200', 'visible': True, 'order': 1001}, {'symbol': 'ESP35', 'visible': True, 'order': 1002}, {'symbol': 'FRA40', 'visible': True, 'order': 750}, {'symbol': 'GER30', 'visible': True, 'order': 650}, {'symbol': 'HKG33', 'visible': True, 'order': 1005}, {'symbol': 'JPN225', 'visible': True, 'order': 1007}, {'symbol': 'NAS100', 'visible': True, 'order': 1008}, {'symbol': 'SPX500', 'visible': True, 'order': 1010}, {'symbol': 'UK100', 'visible': True, 'order': 350}, {'symbol': 'US30', 'visible': True, 'order': 1950}, {'symbol': 'Copper', 'visible': True, 'order': 101600}, {'symbol': 'CHN50', 'visible': True, 'order': 1020}, {'symbol': 'EUSTX50', 'visible': True, 'order': 103500}, {'symbol': 'USDOLLAR', 'visible': True, 'order': 450}, {'symbol': 'US2000', 'visible': True, 'order': 1060}, {'symbol': 'USOil', 'visible': True, 'order': 2001}, {'symbol': 'UKOil', 'visible': True, 'order': 2002}, {'symbol': 'SOYF', 'visible': True, 'order': 2003}, {'symbol': 'NGAS', 'visible': True, 'order': 201500}, {'symbol': 'WHEATF', 'visible': True, 'order': 2020}, {'symbol': 'CORNF', 'visible': True, 'order': 2021}, {'symbol': 'Bund', 'visible': True, 'order': 300100}, {'symbol': 'XAU/USD', 'visible': True, 'order': 150}, {'symbol': 'XAG/USD', 'visible': True, 'order': 550}, {'symbol': 'EMBasket', 'visible': True, 'order': 6001}, {'symbol': 'JPYBasket', 'visible': True, 'order': 6002}, {'symbol': 'BTC/USD', 'visible': True, 'order': 8001}, {'symbol': 'BCH/USD', 'visible': True, 'order': 8002}, {'symbol': 'ETH/USD', 'visible': True, 'order': 8003}, {'symbol': 'LTC/USD', 'visible': True, 'order': 8004}, {'symbol': 'XRP/USD', 'visible': True, 'order': 8005}, {'symbol': 'CryptoMajor', 'visible': True, 'order': 8006}, {'symbol': 'EOS/USD', 'visible': True, 'order': 8007}, {'symbol': 'XLM/USD', 'visible': True, 'order': 8011}, {'symbol': 'USEquities', 'visible': True, 'order': 9007}]}}

hope this help
-Lei



CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage.

74.74% of retail investor accounts lose money when trading CFDs with this provider.

You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Trading Forex/CFDs on margin carries a high level of risk and may not be suitable for all investors. Leverage can work against you. The products are intended for retail, professional and eligible counterparty clients. Retail clients who maintain account(s) with Forex Capital Markets Limited ("FXCM LTD") could sustain a total loss of deposited funds but are not subject to subsequent payment obligations beyond the deposited funds but professional clients and eligible counterparty clients could sustain losses in excess of deposits. Clients who maintain account(s) with FXCM Australia Pty. Limited (“FXCM AU”), FXCM South Africa (PTY) Ltd (“FXCM ZA”) or FXCM Markets Limited (“FXCM Markets”) could sustain losses in excess of deposits. Prior to trading any products offered by FXCM LTD<https://www.fxcm.com/uk/>, inclusive of all EU branches, FXCM AU<https://www.fxcm.com/au/>, FXCM ZA<https://www.fxcm.com/za/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. The information provided by FXCM AU is intended for residents of Australia and is not directed at any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation. Please read the full Terms and Conditions<https://www.fxcm.com/au/legal/terms-conditions/>. FXCM South Africa (PTY) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534. FXCM Markets Limited ("FXCM Markets") is incorporated in Bermuda as an operating subsidiary within the FXCM group. FXCM Markets is not required to hold any financial services license or authorization in Bermuda to offer its products and services. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.

**Comment by rkyleg** [comment]
wtaf kind of bot response is that? and to auto-close? horrible user engagement, we wont be using this api. @dbvcode if you do get a response or find a solution...let me know.

**Comment by dbvcode** [comment]
@rkyleg the solution is Oanda :)

The ID's don't actually match and after playing around with the FXCM API my demo account got disabled with no notice.
FXCM has websockets and Oanda doesn't. That's the only bummer, but I can live with that as their API is snappy, user experience on their platform is better and support is good. I even got called on the phone by Oanda's staff after making the demo account to check if all is good, if I can get in the platform, if I need anything.

[So, this is the answer for me](https://github.com/escwdev/oanda-node-api)

**Comment by hamletjunior** [comment]
Hi Guys!

I've been trying a few APIs to automate my forex trading strategy for a while .

I tested Dukascopy Java API, Oanda Rest API, FXCM Rest API and FXCM Java API.

**Oanda's Rest API** is the best by far....but that's not everything. Oanda's data is not as good as FXCM. FXCM Has more volume and the movements are more reliable compared to Oanda's data. If your strategy depends on supports and resistances, you're going to have a little struggle with Oanda.

The documentation on Oanda's API is excellent and the tech support is awesome. But my main need is data...and FXCM has the best data so far.

**Dukascopy Java API** is really nice, easy to use, but it's a nightmare to use it on a corporate environment when you have a firewall. Behind it's cuteness it is a real mess for system admins to deal with it's bizarre connection scheme.

I tried using the **FXCM Rest Api**, but since my automation need 24x5 availability, I had problems with that. Every now and then FXCM has some unavailability periods to login to the rest api that last for more than 30 minutes....and that's a no go for me.

Now I'm using **FXCM's Java API**. It's an old API, but it works. It's extremely reliable and you won't lose a candle with it. But you will have to learn to use Threads to use it properly. Otherwise you'll end up with a lot of race conditions on your code.

Well, if you have experiences to share, share then, please!

Hope it helps!

**Comment by dbvcode** [comment]
Let's chat about stuff if you want, but I feel this github issue is not the place to do it and it's also offtopic.
You can find me as  @MrP_123 on Telegram

**Comment by FXCMAPI** [comment]
Hi

Our rest API use socket and it is stateful connection, it push the table update to client side via socket so client won't need calculate the PnL. but you need to maintain the socket, which sometime can be challenge.   
Oanda use stateless connection, that based on request and response mode that don't need to maintain the socket,
our Java API is more stable and been used by many clients. 
you can check sample code and doc at here https://github.com/fxcm/JavaAPI

**Comment by BrendanL42** [comment]
Check this link out, I have found a solution 

https://fxcm-api.readthedocs.io/en/latest/restapi.html#offer-ids
