### ISSUE TITLE
Problem reconnecting

### ISSUE THREAD

**Issue by RojoCT** [fxcm/RestAPI#131]
When I lose the connection, sometimes just reconnect perfectly but then again like an hour later I lose the connection again, then it reconnect, and 30 minutes later lose again and this time it can not reconnect and give me the error: `Can not find FXCM Server`

I only make a call to the API every 5 minutes so i think that's not the problem, what I'm doing wrong?
How should I reconnect?

I've been trying different things for like 4 months. So please help would be kindly appreciated.

Thanks.

**Comment by FXCMAPI** [comment]
Hi 
Please be aware that we use socket and it is stateful connection. 
Our server compare the Bearer token string (Bearer + SessionID + Token) for each your request.  request/post
So please make sure your previous session is closed, otherwise our system will disconnect if your Bearer string is different

**Comment by RojoCT** [comment]
How can I see the old Bearer tokens or the active token in the server, and how can I close the old tokens? 

Thanks for your reply.

**Comment by FXCMAPI** [comment]
it is on our server side. you can;t get those information. 
the best way is catch the event, like error/disconnect event and close the socket and shake hand with server to get the new socket ID.
