### ISSUE TITLE
after connect I subscribe many messages every seconds over minutes

### ISSUE THREAD

**Issue by thosch-lab** [fxcm/RestAPI#137]
hi,

i want to connect to FXCM via fxcmpy I use the version 1.2.8
CODE:##

con = fxcmpy.fxcmpy(config_file='fxcm.cfg')
print("Is connected:", con.is_connected())
sys.exit()

and then I receive many messages every second over minutes ? I don't understand it - why ?

But I don’t want it

Thats a demo account …

Engine.IO connection established
Attempting WebSocket upgrade to wss://api-demo.fxcm.com:443/socket.io/?access_token=e9a452e76cd3041d0dbd9ed76ee72a6b720d843e&agent=pythonquants&wait_for_connection=False&transport=websocket&EIO=3
WebSocket upgrade was successful
Sending packet PING data None
Socket established: <socketio.client.Client object at 0x7fc4bb34cb20>.
Received packet PONG data None
Received packet MESSAGE data 0
Namespace / is connected
Connection established.
Received packet MESSAGE data 2["CHN.TECH","{\"Updated\":1619624945574,\"Rates\":[5653.704000000001,5664.974,5737.432,5632.503],\"Symbol\":\"CHN.TECH\"}"]
Received event "CHN.TECH" [/]
Received packet MESSAGE data 2["USDOLLAR","{\"Updated\":1619624945710,\"Rates\":[11741.5,11743.5,11770.5,11736.8],\"Symbol\":\"USDOLLAR\"}"]

thanks for any ideas 

thosch

**Comment by FXCMAPI** [comment]
Hello Thomas

Our Rest API has two modes, request/response (snapshot) and subscribe/update (update).
Snapshot mode is useful retrieving historical price. Which give you bulk data in one request.
Subscribe mode is for live stream update, like market live update. Monitor account table or open position table. 

The logs shows you subscribe market price which is why you got price update event pushed to your side via socket. 
If you don’t want it, please unsubscribe it 

Hope this help 
-Lei
