### ISSUE TITLE
endpoint 'trading/open_trade' returns an orderId that does not match the tradeId

### ISSUE THREAD

**Issue by RiccardoNizzolo** [fxcm/RestAPI#32]
If I open a trade with the following code:

```
 method = 'trading/open_trade'
 params = {'account_id': ACCOUNT_ID,
                  'symbol': symbol,
                  'is_buy': is_buy,
                  'rate': 0.0, 'amount': amount, 'at_market': 0.0, 'order_type': 'AtMarket',
                  'time_in_force': 'GTC', 'is_in_pips': 'false'}
 req = requests.post('%s:443/%s' % (TRADING_API_URL, method),
                            headers=self.request_headers, data=params,
                            proxies={})
```
I get the following response:
``
'{"response":{"executed":true},"data":{"type":0,"orderId":324980343}}'
``

However the key **orderid** does not match anything. Indeed if I ask for the orders i get an empty response:
``
requests.get('%s:443/%s' % (TRADING_API_URL, method),
                                headers=self.request_headers, params={'models': ['Order']},
                                proxies={})
``
Meanwhile  if try to get all open positions I get only the **tradeid** key that does not match orderid:
``
requests.get('%s:443/%s' % (TRADING_API_URL, method),
                                headers=self.request_headers, params={'models': ['Order']},
                                proxies={})
``
b'{"response":{"executed":true},"open_positions":[{"t":1,"ratePrecision":2,"**tradeId":"154414462", .....
``
**Also the open_trade method of FXCMpy looks broken and returns a None**

**Comment by FXCMAPI** [comment]
Hello Riccardo

Here is how it works.
Orders were first been created in order table. You will get the order id in call back
If it is a market order, it will add a entry in open position table and  deleted from order table.
If you subscribe the order table and open position table.
You will see those activities on both order table and open position table,
At the same time you will see order id and trade ID during insert in open position table which you can link which order to which ticket id.

If order are entry order, it will stay on order table waiting the price been triggered

https://apiwiki.fxcorporate.com/api/RestAPI/Socket%20REST%20API%20Specs.pdf

Hope this help
Best regards
Lei



CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage.

73.62% of retail investor accounts lose money when trading CFDs with this provider.

You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Trading Forex/CFDs on margin carries a high level of risk and may not be suitable for all investors as you could sustain losses in excess of deposits. Leverage can work against you. The products are intended for retail, professional and eligible counterparty clients. For clients who maintain account(s) with Forex Capital Markets Limited ("FXCM LTD"), retail clients could sustain a total loss of deposited funds but are not subject to subsequent payment obligations beyond the deposited funds and professional clients could sustain losses in excess of deposits. Prior to trading any products offered by Forex Capital Markets Limited<https://www.fxcm.com/uk/>, inclusive of all EU branches, FXCM Australia Pty. Limited<https://www.fxcm.com/au/>, FXCM South Africa (PTY) Ltd<https://www.fxcm.com/za/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. FXCM South Africa (PTY) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534. FXCM Markets Limited ("FXCM Markets") is an operating subsidiary within the FXCM Group. FXCM Markets is not regulated and not subject to the regulatory oversight that govern other FXCM Group entities, which includes but is not limited to the Financial Conduct Authority, Financial Sector Conduct Authority, and the Australian Securities and Investments Commission. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.

**Comment by RiccardoNizzolo** [comment]
Thank you Lei for the prompt reply!

so if my understanding is correct, in order to get the execution price of an order at market i need the following steps:
1) open a thread that listen to orders and open_positions tables via socket
2) execute the order and get order_id
3) wait for socket output and match the order id with the trade id
4) get the price from trade id

am I right?

Since every open_position seems generated from an orderid I have another question. There is a plan to extend the API and include the orderid key inside the open position table?

Best
Riccardo

**Comment by fxcm-dhalpert** [comment]
you can find an example at https://github.com/fxcm/RestAPI#orderid-vs-tradeid
the order ID might be included in OpenPositions table, no ETA

**Comment by FXCMAPI** [comment]
close this. please reach to api@fxcm.com if you still have issue.
