### ISSUE TITLE
Cannot get streaming data (subscribe_market_data error)

### ISSUE THREAD

**Issue by Gongyu0226** [fxcm/RestAPI#64]
Hello there

I tried to get streaming data, here is my code：
/////////////////////////////////////////
import fxcmpy

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

api=fxcmpy.fxcmpy(config_file='fxcm.cfg',server='demo')

def output(data, dataframe):
    print('%3d | %s | %s | %6.5f, %6.5f' % (len(dataframe), data['Symbol'], pd.to_datetime(int(data['Updated']), unit='ms'),data['Rates'][1], data['Rates'][1]))
    
api.subscribe_market_data('EUR/USD', (output,))  

api.get_last_price('EUR/USD')

api.unsubscribe_market_data('EUR/USD')  
///////////////////////////////////

Its error message is as follows:

////////////////////////////
|ERROR|2020-03-08 17:27:23,188|Server reports an error: {'executed': False, 'error': 'No price stream for EUR/USD'}.
|ERROR|2020-03-08 17:27:23,219|URL: https://api-demo.fxcm.com:443/subscribe
|ERROR|2020-03-08 17:27:23,253|Headers: {'User-Agent': 'request', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Authorization': 'Bearer YcfmU78qmdP4Es5MAAGyea964c8323c37cb7897a198edd5d3f02a702ffd2', 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': '15'}
|ERROR|2020-03-08 17:27:23,286|Params: {'pairs': 'EUR/USD'}
|ERROR|2020-03-08 17:27:23,336|Bearer token: Bearer YcfmU78qmdP4Es5MAAGyea964c8323c37cb7897a198edd5d3f02a702ffd2
|ERROR|2020-03-08 17:27:23,369|Connection status: established
|ERROR|2020-03-08 17:27:23,403|Socket session id: YcfmU78qmdP4Es5MAAGy
|ERROR|2020-03-08 17:27:23,436|Can not parse server answer to json object: {"response":{"executed":false,"error":"No price stream for EUR/USD"},"pairs":[]}.
Traceback (most recent call last):
  File "<pyshell#31>", line 1, in <module>
    api.subscribe_market_data('EUR/USD', (output,))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fxcmpy/fxcmpy.py", line 749, in subscribe_market_data
    data = data['pairs'][0]
IndexError: list index out of range
////////////////////////////

I have confirmed if I have a link to the API, but I just cannot get the information.

How do I resolve this? Thank you.

**Comment by FXCMAPI** [comment]
Hello
Your token is working fine on my side.
Looks like you have not connect yet.
Please make sure you have latest fxcmpy 1.2.6 and latest python-socketio 4.4.0

[cid:image001.png@01D5F531.6FCA28E0]


thanks
Lei


CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage.

69.66% of retail investor accounts lose money when trading CFDs with this provider.

You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Trading Forex/CFDs on margin carries a high level of risk and may not be suitable for all investors. Leverage can work against you. The products are intended for retail, professional and eligible counterparty clients. Retail clients who maintain account(s) with Forex Capital Markets Limited ("FXCM LTD") could sustain a total loss of deposited funds but are not subject to subsequent payment obligations beyond the deposited funds but professional clients and eligible counterparty clients could sustain losses in excess of deposits. Clients who maintain account(s) with FXCM Australia Pty. Limited (“FXCM AU”), FXCM South Africa (PTY) Ltd (“FXCM ZA”) or FXCM Markets Limited (“FXCM Markets”) could sustain losses in excess of deposits. Prior to trading any products offered by FXCM LTD<https://www.fxcm.com/uk/>, inclusive of all EU branches, FXCM AU<https://www.fxcm.com/au/>, FXCM ZA<https://www.fxcm.com/za/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. The information provided by FXCM AU is intended for residents of Australia and is not directed at any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation. Please read the full Terms and Conditions<https://www.fxcm.com/au/legal/terms-conditions/>. FXCM South Africa (PTY) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534. FXCM Markets Limited ("FXCM Markets") is incorporated in Bermuda as an operating subsidiary within the FXCM group. FXCM Markets is not required to hold any financial services license or authorization in Bermuda to offer its products and services. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.

**Comment by Gongyu0226** [comment]
I have upgraded to the latest version.
I would like to ask whether there will be no data because of time.
For example: Sunday night.

**Comment by Gongyu0226** [comment]
![螢幕快照 2020-03-08 下午10 32 08](https://user-images.githubusercontent.com/32503810/76164789-a6cd2780-618c-11ea-8856-6f6f60687787.png)

**Comment by FXCMAPI** [comment]
market is closed on Sunday around 5:00 PM EST.

**Comment by mabedis** [comment]
Hello,

I'm using fxcmpy version 1.2.6 and when i run my code I confront with an error.

The piece of code:

> import fxcmpy
> con = fxcmpy.fxcmpy(config_file='fxcm.cfg')
> con.subscribe_market_data('EUR/USD')

And the error:

> fxcm/env/lib/python3.7/site-packages/fxcmpy/fxcmpy.py", line 749, in subscribe_market_data
>     data = data['pairs'][0]
> IndexError: list index out of range

I've also followed the instructions in other threads and I removed socketIO-client==0.7.2 and just keep the python-socketio==4.5.0. But still the same error happens.

Also when I comment the specified method, my other methods works properly as below:

> print(con.get_subscribed_symbols())
Returns --> []

> print(con.is_subscribed('EUR/USD'))
Returns --> False

> print(con.get_last_price('EUR/USD'))
Returns --> in get_last_price    raise ValueError('Symbol %s is not subscripted' % symbol)
ValueError: Symbol EUR/USD is not subscripted

Also I can correctly connect to server and I can easily extract other data and visualize them. So as I checked there is no connection problem. The error raises only from the 

> subscribe_market_data('EUR/USD')

 method.

Is there any other solution?

**Comment by FXCMAPI** [comment]
Dear clients

We are looking into it, will update you the progress

Best regards
Lei


CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage.

69.66% of retail investor accounts lose money when trading CFDs with this provider.

You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Trading Forex/CFDs on margin carries a high level of risk and may not be suitable for all investors. Leverage can work against you. The products are intended for retail, professional and eligible counterparty clients. Retail clients who maintain account(s) with Forex Capital Markets Limited ("FXCM LTD") could sustain a total loss of deposited funds but are not subject to subsequent payment obligations beyond the deposited funds but professional clients and eligible counterparty clients could sustain losses in excess of deposits. Clients who maintain account(s) with FXCM Australia Pty. Limited (“FXCM AU”), FXCM South Africa (PTY) Ltd (“FXCM ZA”) or FXCM Markets Limited (“FXCM Markets”) could sustain losses in excess of deposits. Prior to trading any products offered by FXCM LTD<https://www.fxcm.com/uk/>, inclusive of all EU branches, FXCM AU<https://www.fxcm.com/au/>, FXCM ZA<https://www.fxcm.com/za/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. The information provided by FXCM AU is intended for residents of Australia and is not directed at any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation. Please read the full Terms and Conditions<https://www.fxcm.com/au/legal/terms-conditions/>. FXCM South Africa (PTY) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534. FXCM Markets Limited ("FXCM Markets") is incorporated in Bermuda as an operating subsidiary within the FXCM group. FXCM Markets is not required to hold any financial services license or authorization in Bermuda to offer its products and services. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.

**Comment by fxcm-dhalpert** [comment]
Please try to use the subscribe_market_data() with callback function, for example:

def print_data(data, dataframe):
    print('%6d | %s | %s, %s, %s, %s, %s'
          % (len(dataframe), data['Symbol'],
             pd.to_datetime(int(data['Updated']), unit='ms'),
             data['Rates'][0], data['Rates'][1], data['Rates'][2],
             data['Rates'][3]))

con.subscribe_market_data("GBP/USD", (print_data,))

**Comment by mabedis** [comment]
It's working now.
Your example worked correctly. Also I checked the code without the callback function, just testing it according to my issue and now it works without any problem.
Thank you and thanks for your support.

**Comment by mabedis** [comment]
> Please try to use the subscribe_market_data() with callback function, for example:
> 
> def print_data(data, dataframe):
> print('%6d | %s | %s, %s, %s, %s, %s'
> % (len(dataframe), data['Symbol'],
> pd.to_datetime(int(data['Updated']), unit='ms'),
> data['Rates'][0], data['Rates'][1], data['Rates'][2],
> data['Rates'][3]))
> 
> con.subscribe_market_data("GBP/USD", (print_data,))

It's working now.
Your example worked correctly. Also I checked the code without the callback function, just testing it according to my issue and now it works without any problem.
Thank you and thanks for your support.
