### ISSUE TITLE
AttributeError importing fxcmpy

### ISSUE THREAD

**Issue by joelfreybott** [fxcm/RestAPI#65]
importing fxcmpy created error `socketio not found`. I had `socketIO` and `socketIO-client` installed.
Installing socketio then brought following error:

AttributeError                            Traceback (most recent call last)
<ipython-input-5-dccc53ad16b2> in <module>
----> 1 import fxcmpy

/opt/conda/lib/python3.7/site-packages/fxcmpy/__init__.py in <module>
----> 1 from fxcmpy.fxcmpy import fxcmpy as fxcmpy
      2 from fxcmpy.fxcmpy_open_position import fxcmpy_open_position
      3 from fxcmpy.fxcmpy_closed_position import fxcmpy_closed_position
      4 from fxcmpy.fxcmpy_order import fxcmpy_order
      5 from fxcmpy.fxcmpy_oco_order import fxcmpy_oco_order
`
/opt/conda/lib/python3.7/site-packages/fxcmpy/fxcmpy.py in <module>
     30 from urllib.parse import unquote
     31 
---> 32 socketIO = socketio.Client()
     33 socket = socketIO;
     34 

AttributeError: module 'socketio' has no attribute 'Client'

**Comment by FXCMAPI** [comment]
Hello

We had a release on 1/24 that we don’t support socketio-client anymore
We use python-socketio instead.
Please make sure you have latest fcmpy 1.2.6 and python-socketio 1.2.6

https://github.com/fxcm/RestAPI

thanks
Lei


CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage.

69.66% of retail investor accounts lose money when trading CFDs with this provider.

You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Trading Forex/CFDs on margin carries a high level of risk and may not be suitable for all investors. Leverage can work against you. The products are intended for retail, professional and eligible counterparty clients. Retail clients who maintain account(s) with Forex Capital Markets Limited ("FXCM LTD") could sustain a total loss of deposited funds but are not subject to subsequent payment obligations beyond the deposited funds but professional clients and eligible counterparty clients could sustain losses in excess of deposits. Clients who maintain account(s) with FXCM Australia Pty. Limited (“FXCM AU”), FXCM South Africa (PTY) Ltd (“FXCM ZA”) or FXCM Markets Limited (“FXCM Markets”) could sustain losses in excess of deposits. Prior to trading any products offered by FXCM LTD<https://www.fxcm.com/uk/>, inclusive of all EU branches, FXCM AU<https://www.fxcm.com/au/>, FXCM ZA<https://www.fxcm.com/za/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. The information provided by FXCM AU is intended for residents of Australia and is not directed at any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation. Please read the full Terms and Conditions<https://www.fxcm.com/au/legal/terms-conditions/>. FXCM South Africa (PTY) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534. FXCM Markets Limited ("FXCM Markets") is incorporated in Bermuda as an operating subsidiary within the FXCM group. FXCM Markets is not required to hold any financial services license or authorization in Bermuda to offer its products and services. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.
