### ISSUE TITLE
Unexpected "Unauthorized" error while subscribing to market data

### ISSUE THREAD

**Issue by Iltotore** [fxcm/RestAPI#77]
Hello,

I'm trying to subscribe to FXCM's market data using Scala. I firstly open the socket.io connexion and the server responds positively:
```json
0{"sid":"cJaWmJyJyb5GamO3AXar","upgrades":[],"pingInterval":25000,"pingTimeout":5000}
```

then, I'm sending a subscription request to `api-demo.fxcm.com/subscribe` (note that I use a demo account).

- Request: 
```
HttpRequest(HttpMethod(POST),https://api-demo.fxcm.com:443/subscribe,List(User-Agent: request, Accept: application/json, Content-Type: application/x-www-form-urlencoded, Authorization: Bearer cJaWmJyJyb5GamO3AXarXXXXXXXXX))
```
XXXXXXX representing the token (the length is not significant)

- JSON Data:
```json
{
"pairs": "EUR/USD"
}
```

But I got an "Unauthorized" error:
```json
{
  "response" : {
    "executed" : false,
    "error" : "Unauthorized"
  },
  "pairs" : [
  ]
}
```

I tried:
- Re-Checking my headers
- Waiting (in case of a potential REST API problem)
- Resetting my token

But I'm still getting this error. Note that the API send regularly a custom message (id 4) containing "0".

**Comment by FXCMAPI** [comment]
Dear client

Our authentication is Bearer + SessionID + Token.  It use socket to push the update to client.
First client need to obtain socketID by using token, then client build the Bearer string for authentication.
After been authorized, client need to pass the Bearer string for each request, because our system will check validate your string on our side.

If you keep reconnecting, that previous session may still live  that server detected the session ID you provide is not sync with server, you will get “unauthorized” error.

Hope this help
-Lei


CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage.

75.38% of retail investor accounts lose money when trading CFDs with this provider.

You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Trading Forex/CFDs on margin carries a high level of risk and may not be suitable for all investors. Leverage can work against you. The products are intended for retail, professional and eligible counterparty clients. Retail clients who maintain account(s) with Forex Capital Markets Limited ("FXCM LTD") could sustain a total loss of deposited funds but are not subject to subsequent payment obligations beyond the deposited funds but professional clients and eligible counterparty clients could sustain losses in excess of deposits. Clients who maintain account(s) with FXCM Australia Pty. Limited (“FXCM AU”), FXCM South Africa (PTY) Ltd (“FXCM ZA”) or FXCM Markets Limited (“FXCM Markets”) could sustain losses in excess of deposits. Prior to trading any products offered by FXCM LTD<https://www.fxcm.com/uk/>, inclusive of all EU branches, FXCM AU<https://www.fxcm.com/au/>, FXCM ZA<https://www.fxcm.com/za/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. The information provided by FXCM AU is intended for residents of Australia and is not directed at any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation. Please read the full Terms and Conditions<https://www.fxcm.com/au/legal/terms-conditions/>. FXCM South Africa (PTY) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534. FXCM Markets Limited ("FXCM Markets") is incorporated in Bermuda as an operating subsidiary within the FXCM group. FXCM Markets is not required to hold any financial services license or authorization in Bermuda to offer its products and services. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.

**Comment by Iltotore** [comment]
I'm already getting the new sid before creating the bearer access. Still getting this error.
